### PR TITLE
Relax base-compat; Haskell-CI on github for GHC 7.4 - 9.2

### PR DESCRIPTION
**Pull request by andreasabel**
- allow base-compat 0.12
- new github workflow: Haskell-CI for GHC 7.4 - 9.2
- rm travis.yml
- bump cabal version to 1.10
- format dependency list

Successful CI run at: https://github.com/andreasabel/wl-pprint-text/actions/runs/1553205633

Revision performed at: https://hackage.haskell.org/package/wl-pprint-text-1.2.0.1/revisions/
No re-release needed.

### CODE REVIEW

**Comment by andreasabel** [comment]
Ping @ivan-m

**Comment by georgefst** [comment]
`text` can also be bumped to include 2.0 (well, it builds, there are no tests to run). Do you want to handle that in this PR?

**Comment by andreasabel** [comment]
@georgefst : Are you maintainer with commit rights?

**Comment by georgefst** [comment]
> @georgefst : Are you maintainer with commit rights?

No.

**Comment by andreasabel** [comment]
Ok, I see.
Well, I won't update a PR if I have not seem a reaction of a maintainer.  My extra work could simply be lost (like my original work on this PR).
ping @ivan-m

**Comment by georgefst** [comment]
Sure. To clarify, I was about to open a PR with just the `text` bump. But seeing as this PR has already consumed all others in to a single "get this package up to date" change, I thought it might make sense to batch the `text` change up with the rest.

**Comment by andreasabel** [comment]
Once CI is up and running, it will be easier for the maintainer to approve of a version bump PR, this is my hope...

**Comment by ivan-m** [comment]
Sorry, I don't get on GitHub much so I didn't see the PR. Thanks @andreasabel !

**Pull request merged**
